### ISSUE TITLE
Is mainstream SDK still against the idea proposed in this library ? 

### ISSUE THREAD

**Issue by allan-simon** [B-Galati/monolog-sentry-handler#29]
As per this PR https://github.com/getsentry/sentry-php/pull/1199  it seems to contradict with  the reason given in `What are the differences with the official Monolog Sentry handler?`

**Comment by B-Galati** [comment]
Haha thank you for notifying! I was not aware of it. They may have changed their mind then, which is great!

IIRC, several PR try to add a Monolog breadcrumb handler back to the SDK. Because, yes the SDK was supporting breadcrumbs back in the day: https://github.com/getsentry/sentry-php/blob/1.x/lib/Raven/Breadcrumbs/MonologHandler.php.

This lib could be deprecated once the SDK integrated the handler :+1:

**Comment by allan-simon** [comment]
awesome !

**Comment by Wirone** [comment]
What a timing they have 🙈 After so much work you did in #25 recently, Sentry introduces built-in support for Monolog breadcrumbs 😅

**Comment by B-Galati** [comment]
That's cool! I have to check how it works before deprecating mine though :+1: 

Don't have time these days :see_no_evil:

**Comment by B-Galati** [comment]
That's cool! I have to check how it works before deprecating mine though :+1: 

Don't have time these days :see_no_evil:

**Comment by B-Galati** [comment]
So I did some tests and the new Handler does not do the same job.

I added [more info in the FAQ](https://github.com/B-Galati/monolog-sentry-handler#what-are-the-differences-with-the-official-monolog-sentry-handlers): basically the new handler is made to work with default integrations with error handlers, etc.
