### ISSUE TITLE
Optionally flush events

### ISSUE THREAD

**Issue by thomasvargiu** [B-Galati/monolog-sentry-handler#3]
Can we optionally flush events?

It can be useful to change the default behaviour to do something like this:

```php
$flushEvents = 'cli' === \PHP_SAPI;
$handler = new SentryHandler($hub, Logger::WARNING, true, $flushEvents);
```

...or much better with a setter method.

Web performance will improve.

**Comment by B-Galati** [comment]
Yes performance could be really bad if many events are sent and that's why this handler should be used with `FingersCrossedHandler` and/or a `BufferHandler`. Check out the symfony guide for an [example](https://github.com/B-Galati/monolog-sentry-handler/blob/master/doc/guide-symfony.md#step-2-configure-monolog).

I would suggest to use the [spool transport](https://docs.sentry.io/platforms/php/#spooltransport) of Sentry SDK if you need to send events later but IMHO it is much simpler to use a `FingersCrossedHandler` with a `BufferHandler` and when in long running process you would reset Monolog logger from time to time like [shown](https://github.com/B-Galati/monolog-sentry-handler/blob/master/doc/guide-symfony.md#step-4-flush-monolog-on-each-handled-symfony-messenger-message) in the Symfony guide.

At the end I am ok if you are willing to add this option if you think it fits your needs.

**Comment by B-Galati** [comment]
Please check out this new [doc](https://github.com/B-Galati/monolog-sentry-handler/blob/1.2.0/doc/extension-points.md) that should answer your need ;-)
